project:
  type: website

website:
  title: "Pepijn Vink"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - icon: bi-box-arrow-up-right
        href: https://pepijnvink.github.io/CV/PepijnVinkCV.pdf
        text: CV
      - href: current projects.qmd
        text: Current Projects

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
