project:
  type: website

website:
  title: "Pepijn Vink"
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: current projects.qmd
        text: Current Projects
      - href: CV.qmd
        text: CV

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
