project:
  type: website

website:
  title: "Pepijn Vink"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: current projects.qmd
        text: Current Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



